/**
 * App-wide icon vocabulary backed by Phosphor React. Legacy-facing names keep
 * UI components focused on meaning while the visual system stays consistent.
 */
export type { Icon } from "@phosphor-icons/react";
export {
  Warning as AlertTriangle,
  ArrowRight,
  ArrowSquareOut as ExternalLink,
  ArrowUpRight,
  ArrowsClockwise as RefreshCw,
  Bell,
  CalendarDots as CalendarClock,
  CalendarDots as CalendarDays,
  CalendarPlus,
  Camera,
  Check,
  CheckCircle as CheckCircle2,
  CheckCircle as CircleCheckIcon,
  Check as CheckIcon,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRight,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUpIcon,
  Circle,
  Circle as CircleIcon,
  ClipboardText as ClipboardList,
  Clock,
  Clock as Clock3,
  Copy,
  DoorOpen,
  DotsSixVertical as GripVertical,
  DotsSixVertical as GripVerticalIcon,
  DotsThree as MoreHorizontal,
  DotsThree as MoreHorizontalIcon,
  EnvelopeSimple as Mail,
  EnvelopeSimple as EnvelopeIcon,
  FileArrowDown as FileDown,
  FileText,
  FolderSimple as FolderHeart,
  Gift,
  HandHeart as HeartHandshake,
  Handshake,
  Heart,
  House as Home,
  Images,
  Info,
  Info as InfoIcon,
  LinkSimple as Link2,
  ListChecks,
  SpinnerGap as Loader2,
  SpinnerGap as Loader2Icon,
  Lock,
  MagnifyingGlass as Search,
  MagnifyingGlass as SearchIcon,
  MapPin,
  ChatCircle as MessageCircle,
  Minus,
  Minus as MinusIcon,
  Palette,
  PencilSimple as Pencil,
  PaperPlaneRight as Send,
  Phone,
  PiggyBank,
  Plus,
  Printer,
  Confetti as PartyPopper,
  Quotes as Quote,
  Receipt,
  Receipt as ReceiptText,
  FloppyDisk as Save,
  Gear as Settings,
  SignOut as LogOut,
  ShieldCheck,
  ShoppingCart,
  Sparkle as Sparkles,
  SquaresFour as LayoutDashboard,
  SquaresFour as LayoutGrid,
  Target,
  Trash as Trash2,
  TrendUp as TrendingUp,
  Upload,
  User,
  Cursor as MousePointer,
  User as UserRound,
  UserPlus,
  Users,
  Wallet,
  Warning,
  Warning as TriangleAlertIcon,
  X,
  X as XIcon,
  XCircle as OctagonXIcon,
} from "@phosphor-icons/react";